sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t javier/Docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true javier/Docker-react npm run test -- --coverage